### PR TITLE
use cortex-m-quickstart to test that 'it links'

### LINKED ISSUE #13: unbreak nightlies
Our nightlies are failing: https://github.com/knurling-rs/flip-link/actions because our app-template patch doesn't apply anymore.This will likely break every time we update the app-template.. maybe we can come up with a less brittle way to modify the TODOs in the template?

### PR DESCRIPTION
**Pull request by japaric**
closes #13

this PR commits an instance of the quickstart template and removes the app-template patch which was breaking every now and then on nightly

### CODE REVIEW

File: test-flip-link-app/examples/panic.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+#![no_main]
+#![no_std]
+
+// Pick one of these panic handlers:
+
+// `panic!` halts execution; the panic message is ignored
```
Comment (jonas-schievink) [inline test-flip-link-app/examples/panic.rs:6]: I don't think it's ignored, right? It should be printed via semihosting.

```suggestion
```

Comment (japaric) [reply test-flip-link-app/examples/panic.rs:6]: ah, I was removing some of the original code and missed removing these comments, thanks

**Review by jonas-schievink — APPROVED** [review]
