### PR TITLE
Tests for 22

### LINKED ISSUE #26: CI: add regression test for #22
Add regression test for #22.

- add a new test-app folder / package (like `test-flip-link-app`)
- have this app use a manual `memory.x` file -- easiest way to do this may be to *not* use a HAL
- have the `memory.x` use an `INCLUDE` like this:
``` text
MEMORY
{
  FLASH : ORIGIN = 0x00000000, LENGTH = 256K
  RAM : ORIGIN = 0x20000000, LENGTH = 64K
}

INCLUDE empty.x
```
- create an empty `empty.x` file next to the `memory.x`
- have CI cross compile this new test-app to ARM Cortex-M ("it links" test)

### PR DESCRIPTION
**Pull request by Urhengulas**
Also partially depends on #40 and fixes #26, by implementing tests for #22.

### CODE REVIEW

File: tests/verify.rs [hunk 1]
```diff
@@ -1,19 +1,23 @@
...
 const FILES: [&str; 4] = ["crash", "exception", "hello", "panic"];
 /// Compilation target firmware is build for
 const TARGET: &str = "thumbv7m-none-eabi";
 
-#[test]
-fn should_link_example_firmware() -> anyhow::Result<()> {
+#[rstest]
+#[case::normal(true)]
+#[case::custom_linkerscript(false)]
+fn should_link_example_firmware(#[case] default_features: bool) -> anyhow::Result<()> {
```
Comment (japaric) [inline tests/verify.rs:15]: there's a potential race condition here: `rstest` produces *2* `#[test]` functions. These will run in parallel: meaning that 2 `cargo build` processes will run in parallel. Both processes will write an ELF file to `target/thumb/debug/elf`; the instance that takes longer will overwrite the file that the other instance wrote. That file will be open / inspected by the `#[test]` function. There's no guarantee that each `#[test]` function will open the *right* instance: more likely both `#[test]` functions will end up inspecting the same ELF file.

To solve the issue, the `#[test]` functions should run *sequentially*. there's two ways to do that:
- you can pass `--test-threads=1` to the `cargo test` invocation
- you can use a `Mutex` in this file as a semaphore to ensure only *one* `#[test]` function has access to the `target` directory at any time.

Given that these tests are run using the `cargo xtest` command, I think `--test-threads` is a good solution.

**Review by japaric — CHANGES_REQUESTED** [review]
I'm seeing some issues in the implementation and I'm not sure the new test is indeed testing what it's meant to do so I'd like my inline comments to be addressed before a take a closer look at the actual assertions.

File: tests/verify.rs [hunk 2]
```diff
@@ -58,13 +62,19 @@ mod cargo {
...
-    pub fn build_example_firmware(rel_path: &str) -> Assert {
+    pub fn build_example_firmware(rel_path: &str, default_features: bool) -> Assert {
         // append `rel_path` to the current working directory
         let mut firmware_dir = std::env::current_dir().unwrap();
         firmware_dir.push(rel_path);
 
+        // disable default features or use `-v` as a no-op
+        let default_features = match default_features {
+            false => "--no-default-features",
+            true => "-v",
```
[the remark this answers is not in the document]
Comment (Urhengulas) [reply tests/verify.rs:73]: `error: Found argument '' which wasn't expected, or isn't valid in this context`

[the remark this answers is not in the document]
Comment (Urhengulas) [reply tests/verify.rs:73]: I also tried `""` first, but since it didn't work picked `-v` cause it has no effect on the operation afaik.

File: test-flip-link-app/build.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
+fn main() -> anyhow::Result<()> {
+    // include following if hal is excluded (aka. default features are disabled)
+    #[cfg(not(feature = "default"))]
```
[the remark this answers is not in the document]
Comment (Urhengulas) [reply test-flip-link-app/build.rs:3]: Is it good like I did in 5ccfa26?

[the remark this answers is not in the document]
Comment (japaric) [reply test-flip-link-app/build.rs:3]: yeah, that looks good!

File: tests/verify.rs (hunk 1 above)
Comment (Urhengulas) [reply tests/verify.rs:15]: Went forward with the `--test-threads` option in 72e74d33f6a67714a22d53a1b2dae60460430d34.

**Comment by Urhengulas** [comment]
@japaric I've addressed your comments, so I think it is good for a review again 😄

File: test-flip-link-app/examples/crash.rs [hunk 4]
```diff
@@ -4,6 +4,7 @@
 use core::ptr;
 
 use cortex_m_rt::entry;
+#[cfg(feature = "default")]
```
Comment (japaric) [inline test-flip-link-app/examples/crash.rs:7]: thinking more about this: could you use `#[cfg(feature = "lm3s6965")]` here and elsewhere the "default" feature is currently used? I think that "default" doesn't clearly convey what, or which, feature(s) are being checked -- the "default" feature could be enabling several Cargo features (I know it's not in this case).

File: test-flip-link-app/Cargo.toml [hunk 5]
```diff
@@ -9,7 +9,15 @@ version = "0.1.0"
 cortex-m = "0.7"
 cortex-m-rt = "0.6"
 cortex-m-semihosting = "0.3"
-lm3s6965 = "0.1"
 panic-semihosting = { version = "0.5", features = ["exit"] }
 
+# optional
+lm3s6965 = { version = "0.1", optional = true }
```
Comment (japaric) [inline test-flip-link-app/Cargo.toml:15]: I think (but double check) that marking a dependency as optional automatically creates a Cargo feature with the same name: so this line should create a "lm3s6965" feature which you can use in `#[cfg]` statements.

**Review by japaric — APPROVED** [review]
other than my request to use a Cargo feature named "lm3s6965" instead of "default", this looks good to me! feel free to send it to bors with or without my request fulfilled

File: test-flip-link-app/Cargo.toml (hunk 5 above)
Comment (Urhengulas) [reply test-flip-link-app/Cargo.toml:15]: Yes. This works!
